FROM mcr.microsoft.com/dotnet/sdk:9.0-windowsservercore-ltsc2019 AS builder

WORKDIR C:\src
COPY ConfigManagementUI.csproj .
RUN dotnet restore "ConfigManagementUI.csproj"

COPY . .
RUN dotnet build "ConfigManagementUI.csproj" -c Release -o C:\app\build

RUN dotnet publish "ConfigManagementUI.csproj" -c Release -o C:\app\publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0-windowsservercore-ltsc2019

WORKDIR C:\app
COPY --from=builder C:\app\publish .

EXPOSE 5000

ENV ASPNETCORE_URLS=http://+:5000

ENTRYPOINT ["dotnet", "ConfigManagementUI.dll"]
