FROM mcr.microsoft.com/dotnet/sdk:9.0 AS builder

WORKDIR /src
COPY ConfigManagementUI.csproj .
RUN dotnet restore "ConfigManagementUI.csproj"

COPY . .
RUN dotnet build "ConfigManagementUI.csproj" -c Release -o /app/build

RUN dotnet publish "ConfigManagementUI.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0

WORKDIR /app
COPY --from=builder /app/publish .

EXPOSE 5000

ENV ASPNETCORE_URLS=http://+:5000

ENTRYPOINT ["dotnet", "ConfigManagementUI.dll"]
